- name: be sure client.json is copied
  copy:
    src: client.json
    dest: "{{ sensu_home }}/conf.d/client.json"

- name: be sure sensu-client is running and enabled
  service: name=sensu-client state=started enabled=yes
