- name: be sure {{ item }} is installed
  apt:
    name: "{{ item }}"
    state: latest
  with_items:
    - graphite-web
    - graphite-carbon
    - libapache2-mod-wsgi
    - rabbitmq-server
    - redis-server
    - uchiwa

- name: be sure redis-server is running and enabled
  service:
    name: redis-server
    state: started
    enabled: yes

- name: be sure apache2-graphite.conf is copied
  copy:
    src: /usr/share/graphite-web/apache2-graphite.conf
    dest: /etc/apache2/sites-available
    remote_src: True

- name: be sure default virtualhost file is disabled
  command: a2dissite 000-default
  notify: restart apache

- name: be sure graphite virtualhost is enabled
  command: a2ensite apache2-graphite
  notify: restart apache

- name: be graphite database is created
  command: graphite-manage syncdb --noinput
  notify: restart apache
