- name: be sure {{ item }} is installed
  apt:
    name: "{{ item }}"
    state: latest
  with_items:
    - graphite-web
    - graphite-carbon
    - rabbitmq-server
    - redis-server
    - uchiwa

- name: be sure redis-server is running and enabled
  service:
    name: redis-server
    state: started
    enabled: yes

- name: be sure apache2-graphite.conf is copied
  copy:
    src: /usr/share/graphite-web/apache2-graphite.conf
    dest: /etc/apache2/sites-available
    remote_src: True

- name: enable graphite virtualhost
  command: a2ensite apache2-graphite
  notify: restart apache
