- name: be sure {{ item }} is installed
  apt:
    name: "{{ item }}"
    state: latest
  with_items:
    - uchiwa
    - ufw

- name: port {{ item }} allowed in firewall
  ufw:
    rule: allow
    port: "{{ item }}"
    proto: tcp
  with_items: "{{ sensu_server_allowed_ports }}"

- name: enable firewall
  ufw:
    state: enabled
    policy: deny
