- name: "install apt packages"
  apt:
    name: "{{ item }}"
    state: latest
  with_items:
    - graphite-web
    - graphite-carbon
    - libapache2-mod-wsgi
    - rabbitmq-server
    - uchiwa

- name: be sure apache2-graphite.conf is copied
  copy:
    src: /usr/share/graphite-web/apache2-graphite.conf
    dest: /etc/apache2/sites-available
    remote_src: True

- name: be sure graphite database is created
  command: graphite-manage syncdb --noinput
  notify: restart apache

- name: be sure right owner and group are assigned to graphite database
  file:
    path: /var/lib/graphite/graphite.db
    owner: _graphite
    group: _graphite
  notify: restart apache
