- name: be sure {{ item }} is installed
  apt:
    name: "{{ item }}"
    state: latest
  with_items:
    - graphite-web
    - graphite-carbon
    - rabbitmq-server
    - redis-server
    - uchiwa

- name: be sure redis-server is running and enabled
  service:
    name: redis-server
    state: started
    enabled: yes
