##### begin - rabbitmq #####
- name: be sure rabbitmq-server is installed
  yum: name=rabbitmq-server state=latest

- name: be sure rabbitmq-server is running and enabled
  service: name=rabbitmq-server state=started enabled=yes

- name: get vhosts
  command: rabbitmqctl list_vhosts
  register: vhosts
  changed_when: false

- name: add vhost sensu
  command: rabbitmqctl add_vhost /sensu
  when: "'/sensu' not in vhosts.stdout" #http://serverfault.com/a/792721/215599

- name: get users
  command: rabbitmqctl list_users
  register: users
  changed_when: false

- name: add user sensu
  command: rabbitmqctl add_user sensu secret
  when: "'sensu' not in users.stdout"

- name: get permissions
  command: rabbitmqctl list_user_permissions sensu
  register: permissions
  changed_when: false

- name: set permissions sensu
  command: rabbitmqctl set_permissions -p /sensu sensu ".*" ".*" ".*"
  when: "'/sensu\t.*\t.*\t.*' not in permissions.stdout"
##### end - rabbitmq #####



##### begin - redis #####
- name: be sure redis is installed
  yum: name=redis state=latest

- name: be sure redis is running and enabled
  service: name=redis state=started enabled=yes
##### end - redis #####



##### begin - sensu #####
- name: be sure sensu.repo is copied
  copy:
    src: sensu.repo
    dest: /etc/yum.repos.d/sensu.repo

- name: be sure sensu is installed
  yum: name=sensu state=latest

- name: be sure uchiwa is installed
  yum: name=uchiwa state=latest

- name: be sure client.json is copied
  copy:
    src: client.json
    dest: "{{ sensu_home }}/conf.d/client.json"

- name: be sure sensu-client is running and enabled
  service: name=sensu-client state=started enabled=yes

- name: be sure sensu-api is running and enabled
  service: name=sensu-api state=started enabled=yes

- name: be sure sensu-server is running and enabled
  service: name=sensu-server state=started enabled=yes

- name: be sure uchiwa is running and enabled
  service: name=uchiwa state=started enabled=yes

- name: be sure uchiwa.json is copied
  template:
    src: uchiwa.j2
    dest: "{{ sensu_home }}/uchiwa.json"
  register: uchiwa_config
  notify:
    - restart uchiwa
##### end - sensu #####



##### begin - graphite #####

##### end - graphite #####



##### begin - carbon #####

##### end - carbon #####
