- include: RedHat.yml
  when: ansible_os_family == 'RedHat'

- include: Debian.yml
  when: ansible_os_family == 'Debian'

- name: "{{ item }} is running and enabled"
  service:
    name: "{{ item }}"
    state: started
    enabled: true
  with_items:
    - sensu-api
    - sensu-server
    - uchiwa

- name: uchiwa.json is copied
  template:
    src: uchiwa.j2
    dest: "{{ sensu_server_home }}/uchiwa.json"
  notify:
    - restart uchiwa

- name: mailer.json is copied
  template:
    src: mailer.j2
    dest: "{{ sensu_server_conf_d }}/mailer.json"
  notify:
    - restart sensu-server

- name: handler_mailer.json is copied
  copy:
    src: handler_mailer.json
    dest: "{{ sensu_server_conf_d }}/handler_mailer.json"
  notify:
    - restart sensu-server

- name: ssl directory created
  file:
    path: "{{ sensu_server_ssl }}"
    state: directory
  when: uchiwa_ssl is defined
