FROM ubuntu:16.04
RUN apt-get update

# Install Ansible
RUN apt -y install python-setuptools python-dev
RUN easy_install pip
RUN pip install ansible

COPY initctl_faker .
RUN chmod +x initctl_faker && rm -fr /sbin/initctl && ln -s /initctl_faker /sbin/initctl

# Install Ansible inventory file
RUN echo "[local]\nlocalhost ansible_connection=local" > /etc/ansible/hosts
